logging:
  level: WARNING

sources:
  ImdbAdapter:
    file_path: '../static_pipeline/data/raw/imdb_data.csv'
  MetacriticAdapter:
    file_path: '../static_pipeline/data/raw/metacritic_movies.csv'
  MovielensAdapter:
    # Nutzen Sie eine bereits aggregierte Datei, um Verarbeitung zu vereinfachen
    file_path: '../static_pipeline/data/raw/movielens_aggregated.csv'
  RottenTomatoesAdapter:
    file_path: '../static_pipeline/data/raw/rotten_tomatoes_movies.csv'

processing:
  min_ratings_for_superscore: 2

  apply_outlier_treatment: false

  outlier_treatment:
    method: 'cap'
    iqr_faktor: 1.5
    lower_percentile: 0.05
    upper_percentile: 0.95
    
output:
  csv_path: '../static_pipeline/data/processed/test_merge_result.csv'

  analysis: 
    analysis_report_path: "data/analysis_reports/comprehensive_movie_merge_report.txt"
    raw_ratings_output_dir: "data/analysis_reports/01_raw_movie_data_insights"
    final_ratings_output_dir: "data/analysis_reports/02_processed_movie_data_insights"


aux_output_dirs:
  invalid: "../static_pipeline/data/intermediate_adapter_outputs/invalid"
  duplicates: "../static_pipeline/data/intermediate_adapter_outputs/duplicates"